config/routes.rb
Rails.application.routes.draw do
 

  get 'student_plans/new'

  resources :students
  resources :charges
  resources :subscriptions
  resources :student_plans
  resources :billings
  resources :student_charges
  resources :student_subscriptions
  resources :student_subscription_discounts
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" ,:omniauth_callbacks => "omniauth_callbacks"}

  get 'owner' => 'students#owner'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/blog'

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
	validates :first_name, :last_name, :email, :phone_number, presence: true

	belongs_to :user
	belongs_to :splan
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:owner, :show, :new, :create, :edit, :update, :destroy]

  def owner
    @students = Student.where(user: current_user)
  end

  # GET /students
  # GET /students.json
  def index
    @students = Student.all

  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
     @user = current_user
  end

  # GET /students/1/edit
  def edit
    @user = current_user
    @student = Student.find_by(id: params[:id])
    @plan = Splan.find_by!(id: @student.splan_id)
    Stripe.api_key = ENV['@user.access_code'] #replace with @user.access_code
    @publishable_key = ENV['@user.publishable_key'] #replace with @user.publishable_key
 end
  # POST /students
  # POST /students.json
  def create
    @student = current_user.students.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    

    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to owner_path, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:splan_id, :first_name, :last_name, :email, :phone_number, :street_address, :city, :state, :zip, :emergency_contact_name, :emergency_contact_phone, :emergency_contact_relationship, :emergency_medical_info, :belt_size, :uniform_size, :birthday)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="card-content">

  <%= form_for(student) do |f| %>
  <% if student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

    <ul>
      <% student.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
    <div class="input-group">
        <span class="input-group-addon">
            
        </span>
        Plan to subscribe to
        <%= f.collection_select(:splan_id , Splan.where(user: current_user), :id, :name, class: "form-control") %>
            <span class="material-input"></span>
    </div>


  <div class="row">
    <div class="col-md-6">
      <div class="form-group label-floating">
        <label class="control-label">First Name</label>
        <%= f.text_field :first_name, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group label-floating">
        <label class="control-label">Last Name</label>
        <%= f.text_field :last_name, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group label-floating">
        <label class="control-label">Email</label>
        <%= f.email_field :email, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group label-floating">
        <label class="control-label">Phone Number</label>
        <%= f.text_field :phone_number, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
  </div>  

  <div class="row">
    <div class="col-md-12">
      <div class="form-group label-floating">
        <label class="control-label">Street Address</label>
        <%= f.text_field :street_address, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group label-floating">
        <label class="control-label">City</label>
        <%= f.text_field :city, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group label-floating">
        <label class="control-label">State</label>
        <%= f.text_field :state, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group label-floating">
        <label class="control-label">Zip</label>
        <%= f.text_field :zip, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group label-floating">
        <label class="control-label">Emergency Contact</label>
        <%= f.text_field :emergency_contact_name, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group label-floating">
        <label class="control-label">Emergency Contact Number</label>
        <%= f.text_field :emergency_contact_phone, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group label-floating">
        <label class="control-label">Relationship</label>
        <%= f.text_field :emergency_contact_relationship, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group label-floating">
        <label class="control-label">Allergies / Medical</label>
        <%= f.text_field :emergency_medical_info, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group label-floating">
        <label class="control-label">Belt Size</label>
        <%= f.text_field :belt_size, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group label-floating">
        <label class="control-label">Uniform Size</label>
        <%= f.text_field :uniform_size, class: "form-control" %>
        <span class="material-input"></span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group label-floating">
        <label class="control-label">Birthday</label>
        <%= f.date_field :birthday, class: "form-control datetimepicker" %>
        <span class="material-input"></span>
      </div>
    </div>
  </div>  

  <div class="form-group">
    <%= f.submit "Update Student Profile", class: "btn btn-success" %>
  </div>
  <% end %>

</div>

app/views/students/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header" data-background-color="purple">
					<div class="row">
						<div class="col-md-6">
							<h4 class="title">Edit Student Profile</h4>
							<p class="category">Complete or update student profile</p>
						</div>
						<div class="col-md-6 text-right">
							<%= link_to '<i class="material-icons">navigate_before</i> Back'.html_safe, owner_path, class: "btn btn-primary" %>
						</div>
					</div>
				</div>

				<%= render 'form', student: @student %>
				<%= link_to 'Create student plans', student_plans_new_path%>

			 <%=form_for :connect, url: user_stripe_connect_omniauth_authorize_path do |f| %>
                        <%= f.submit "connect to stripe", class: "btn btn-primary" %>
              <%end%>

              <p>
          <%= form_tag student_subscription_path , method: "put" do %>
			  <article>
			    <% if flash[:error].present? %>
			      <div id="error_explanation">
			        <p><%= flash[:error] %></p>
			      </div>
			    <% end %>
			    <label class="amount">
			      <span>Amount: $<%=@plan.amount/100%>.00</span>
			    </label>
			  </article>

			  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			          data-key="<%= @publishable_key %>"
			          data-description="A month's subscription"
			          data-amount= "<%@plan.amount%>"
			          data-email= "<%=@student.email%>"
			          data-panel-label = "pay"
			          data-label= "subscribe student"
			          data-locale="auto"></script>
			<% end %>
			
          </p>
          <p>
          	<div class="actions">
             <%= button_to "cancel Subscription",student_subscription_path, :method=>'delete' %> 
           </div>
          </p>

          <p>
           <%= form_for :splan, url: student_subscription_path,  method: "put" do |f| %>
                
                   <div class="actions">
                    <%= f.submit "Reactivate" %>
                  </div>
            <% end %> 
          </p>
          

			</div>
		</div>

		<div class="col-md-4">
			<div class="card card-profile">
				<div class="card-avatar">
					<a href="#">
						<%= image_tag "missing-person.jpg"%>
					</a>
				</div>

				<div class="card-content">
					<h6 class="category text-gray">Member Since <%= @student.created_at.strftime("%m/%d/%Y") %></h6>
					<h4 class="card-title"><%= @student.first_name %> <%= @student.last_name %></h4>
					<p class="card-description">
						Trains at <%= current_user.school_name %>
					</p>
					<a href="#" class="btn btn-default btn-round">View</a><br>
					 <%= link_to "create a discount",new_student_subscription_discount_path %> 
					 <br><br>

					 <%= form_for :discount, url: student_subscription_discount_path, :method=>'put' do |f| %>
			                <div class="">
			                      <%= f.label 'Choose discount' %>
			                      <%= f.collection_select(:coup_id, Coupon.where(user: current_user),:id,:coup_id) %>
			                  </div>
			                   <div class="actions">
			                    <%= f.submit "claim discount" %>
			                  </div>
           			 <% end %> 
           			 <br><br>

					 <%= form_for :date, url: billing_path, :method=>'put' do |f| %>
			                <div class="">
			                      <%= f.label :date %> <%= f.date_select(:date, :order => [:month, :day, :year]) %>
			                  </div>
			                   <div class="actions">
			                    <%= f.submit "change billing cycle" %>
			                  </div>
           			 <% end %> 
					 
			 <%= form_tag student_charge_path , method: "put" do %>
              <article>
                <% if flash[:error].present? %>
                  <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                  </div>
                <% end %>
                <label class="amount">
                  
                </label>
              </article>

              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= @publishable_key %>"
                      data-description="Update card details"
                       data-label= "update Card Details"
                       data-email= "<%=@student.email%>"
                       data-panel-label = "update Card Details"
                      data-locale="auto"></script>
          <% end %>
           </div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/students/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="purple">
          <div class="row">
           <div class="col-md-6">
            <h4 class="title">Students</h4>
            <p class="category">View, Edit or Delete Students</p>
          </div>
          <div class="col-md-6 text-right">

            <%= link_to 'New Student', new_student_path, class: "btn btn-primary" %>
          </div>
           
        </div>
      </div>
      <div class="card-content table-responsive">
        <table class="table">
          <thead class="text-primary">
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @students.each do |student| %>
            <tr>
              <td><%= student.first_name %></td>
              <td><%= student.last_name %></td>
              <td><%= student.email %></td>
              <td><%= student.phone_number %></td>
              <td>
                <!-- Single button -->
                <div class="btn-group">
                  <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Action <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Show', student %></li>
                    <li><%= link_to 'Edit', edit_student_path(student) %></li>
                    <li><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                  </ul>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>

</div>
</div>

app/views/students/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header" data-background-color="purple">
					<div class="row">
						<div class="col-md-6">
							<h4 class="title">Add Student</h4>
							<p class="category">Create New Student Record</p>
						</div>
						<div class="col-md-6 text-right">
							<%= link_to '<i class="material-icons">navigate_before</i> Back'.html_safe, owner_path, class: "btn btn-primary" %>
						</div>
					</div>
				</div>

				<%= render 'form', student: @student %>

app/views/students/owner.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="purple">
          <div class="row">
           <div class="col-md-6">
            <h4 class="title">Students</h4>
            <p class="category">View, Edit or Delete Students</p>
          </div>
            
          <div class="col-md-6 text-right">
            <%= link_to 'Add student plans ',new_student_plan_path, class: "btn btn-primary" %>
            <%= link_to '<i class="material-icons">person_add</i> New Student'.html_safe, new_student_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      <div class="card-content table-responsive">
        <table class="table">
          <thead class="text-primary">
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @students.each do |student| %>
            <tr>
              <td><%= student.first_name %></td>
              <td><%= student.last_name %></td>
              <td><%= student.email %></td>
              <td><%= student.phone_number %></td>
              <td class="td-actions text-right">
               <%= link_to '<i class="material-icons">person</i>'.html_safe, student, class: "btn btn-info btn-simple" %>
               <%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_student_path(student), class: "btn btn-success btn-simple" %>
               <%= link_to '<i class="material-icons">close</i>'.html_safe, student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-simple" %>
             </td>
           </tr>
           <% end %>
         </tbody>
       </table>

     </div>
   </div>
 </div>

</div>
</div>

app/views/students/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header" data-background-color="purple">
					<div class="row">
						<div class="col-md-6">
							<h4 class="title">Student Profile</h4>
							<p class="category">Complete or update student profile</p>
						</div>
						<div class="col-md-6 text-right">
							<%= link_to '<i class="material-icons">edit</i> Edit'.html_safe, edit_student_path, class: "btn btn-primary" %>
							<%= link_to '<i class="material-icons">navigate_before</i> Back'.html_safe, owner_path, class: "btn btn-primary" %>
						</div>
					</div>
				</div>

				<div class="card-content">

					<%= form_for(@student) do |f| %>

					<div class="row">
						<div class="col-md-6">
							<div class="form-group label-floating">
								<label class="control-label">First Name</label>
								<%= f.text_field :first_name, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group label-floating">
								<label class="control-label">Last Name</label>
								<%= f.text_field :last_name, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6">
							<div class="form-group label-floating">
								<label class="control-label">Email</label>
								<%= f.email_field :email, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group label-floating">
								<label class="control-label">Phone Number</label>
								<%= f.text_field :phone_number, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
					</div>  

					<div class="row">
						<div class="col-md-12">
							<div class="form-group label-floating">
								<label class="control-label">Street Address</label>
								<%= f.text_field :street_address, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-4">
							<div class="form-group label-floating">
								<label class="control-label">City</label>
								<%= f.text_field :city, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
						<div class="col-md-4">
							<div class="form-group label-floating">
								<label class="control-label">State</label>
								<%= f.text_field :state, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
						<div class="col-md-4">
							<div class="form-group label-floating">
								<label class="control-label">Zip</label>
								<%= f.text_field :zip, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6">
							<div class="form-group label-floating">
								<label class="control-label">Emergency Contact</label>
								<%= f.text_field :emergency_contact_name, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group label-floating">
								<label class="control-label">Emergency Contact Number</label>
								<%= f.text_field :emergency_contact_phone, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6">
							<div class="form-group label-floating">
								<label class="control-label">Relationship</label>
								<%= f.text_field :emergency_contact_relationship, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group label-floating">
								<label class="control-label">Allergies / Medical</label>
								<%= f.text_field :emergency_medical_info, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-4">
							<div class="form-group label-floating">
								<label class="control-label">Belt Size</label>
								<%= f.text_field :belt_size, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
						<div class="col-md-4">
							<div class="form-group label-floating">
								<label class="control-label">Uniform Size</label>
								<%= f.text_field :uniform_size, class: "form-control" %>
								<span class="material-input"></span>
							</div>
						</div>
						<div class="col-md-4">
							<div class="form-group label-floating">
								<label class="control-label">Birthday</label>
								<%= f.date_field :birthday, class: "form-control datetimepicker" %>
								<span class="material-input"></span>
							</div>
						</div>
					</div>  

					<% end %>

				</div>


			</div>
		</div>

		<div class="col-md-4">
			<div class="card card-profile">
				<div class="card-avatar">
					<a href="#">
						<%= image_tag "card-profile1.jpg" %>
					</a>
				</div>

				<div class="card-content">
					<h6 class="category text-gray">Member Since <%= @student.created_at.strftime("%m/%d/%Y") %></h6>
					<h4 class="card-title"><%= @student.first_name %> <%= @student.last_name %></h4>
					<p class="card-description">
						Trains at <%= current_user.school_name %>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>