config/routes.rb
Rails.application.routes.draw do
 

  get 'student_plans/new'

  resources :students
  resources :charges
  resources :subscriptions
  resources :student_plans
  resources :billings
  resources :student_charges
  resources :student_subscriptions
  resources :student_subscription_discounts
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" ,:omniauth_callbacks => "omniauth_callbacks"}

  get 'owner' => 'students#owner'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/blog'

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/student_subscription_discounts_controller.rb
class StudentSubscriptionDiscountsController < ApplicationController
	before_action :authenticate_user!
	def new
		@coupon = Coupon.new
	end

#creates a coupon on stripe
	def create
		@user = current_user
		@coupon = @user.coupons.new(coupon_params)
		Stripe.api_key = ENV['@user.access_code'] #replace with @user.access_code

		if @coupon.duration == "once"
		
		Stripe::Coupon.create(
		  :amount_off => @coupon.amount_off,
		  :duration => @coupon.duration,
		  :id => @coupon.coup_id,
		  :currency => @coupon.currency
		)
			@coupon.save

		elsif @coupon.duration == 'forever'
		
		Stripe::Coupon.create(
		  :amount_off => @coupon.amount_off,
		  :duration => @coupon.duration,
		  :id => @coupon.coup_id,
		  :currency => @coupon.currency
		)
			@coupon.save

		else
		Stripe::Coupon.create(
		  :amount_off => @coupon.amount_off,
		  :duration => @coupon.duration,
		  :id => @coupon.coup_id,
		  :duration_in_months => @coupon.duration_in_months,
		  :currency => @coupon.currency
		)
			@coupon.save
		end
			redirect_to root_path
		
	end
#creates a discount/discounts a subscription
	def update
		@user = current_user
		@student = Student.find_by(id: params[:id])
		@plan = Splan.find_by!(id: @student.splan_id)
		@param = Coupon.new(claim_params)
		@coupon = Coupon.find_by(id: @param.coup_id)
		Stripe.api_key = ENV['@user.access_code'] #replace with @user.access_code

		Stripe::Subscription.create(
			  :customer => @student.stripe_id,
			  :plan => @plan.stripe_id,
			  :coupon => @coupon.coup_id,
			)
		redirect_to root_url
	end

	private

	def coupon_params
	    params.require(:coupon).permit(:coup_id,:duration,:duration_in_months,:amount_off,:currency)
	end

	def claim_params
		params.require(:discount).permit(:coup_id,:id)
	end

end

app/helpers/student_subscription_discounts_helper.rb
module StudentSubscriptionDiscountsHelper
end

app/views/student_subscription_discounts/new.html.erb
<h2>Create your coupons</h2>

<%=form_for :coupon, url: student_subscription_discounts_path do|f|%>
	<div class="field">
	    <%= f.label :coupon_name %><br />
	    <%= f.text_field :coup_id, autofocus: true %> e.g. deals
	</div>

	<div class="field">
	    <%= f.label :duration %><br /> 
	    <%= f.text_field :duration, autofocus: true %>use (forever,once,repeating)
	</div>

	<div class="field">
	    <%= f.label :currency %><br />
	    <%= f.text_field :currency, autofocus: true %>use (usd)
	</div>

	<div class="field">
	    <%= f.label :duration_in_months %><br />
	    <%= f.number_field :duration_in_months, autofocus: true %>
	</div>


	<div class="field">
	    <%= f.label :amount_off %><br />
	    <%= f.number_field :amount_off, autofocus: true %>use (100)
	</div>

	<div class="actions">
    	<%= f.submit "Create coupon" %>
 	</div>
<%end%>