config/routes.rb
Rails.application.routes.draw do
 

  get 'student_plans/new'

  resources :students
  resources :charges
  resources :subscriptions
  resources :student_plans
  resources :billings
  resources :student_charges
  resources :student_subscriptions
  resources :student_subscription_discounts
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" ,:omniauth_callbacks => "omniauth_callbacks"}

  get 'owner' => 'students#owner'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/blog'

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
	belongs_to :user
end

app/models/plan.rb
class Plan < ApplicationRecord
	
	has_many :users
end

app/models/splan.rb
class Splan < ApplicationRecord
	has_many :students
	belongs_to :user
end

app/models/student.rb
class Student < ApplicationRecord
	validates :first_name, :last_name, :email, :phone_number, presence: true

	belongs_to :user
	belongs_to :splan
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  #highlights the various roles,you can change as needed
  enum role: [:user, :admin, :silver, :gold, :platinum]

  devise :database_authenticatable, :registerable,:omniauthable,
  :recoverable, :rememberable, :trackable, :validatable
  
  belongs_to :plan
  has_many :students, dependent: :destroy
  has_many :splans, dependent: :destroy
  has_many :coupons, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update, keys: [:school_name, :first_name, :phone_number, :last_name, :street_address, :city, :state, :zip])
	end
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
	before_action :authenticate_user!

	#changes billing interval
	def update
		@student = Student.find_by(id: params[:id])
		@user = current_user
		@params = params[:date]
		@date = Date.new(params[:date]["date(1i)"].to_i,params[:date]["date(2i)"].to_i,params[:date]["date(3i)"].to_i).to_time.to_i
		puts ("#{@date}")
		Stripe.api_key = ENV['@user.access_code'] #replace with @user.access_code
		subscription = Stripe::Subscription.retrieve(@student.sub_id)
			subscription.trial_end = @date
			subscription.prorate = false
			subscription.save
		redirect_to root_path
	end

	
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	
before_action :authenticate_user!
	def new
		@user = current_user
  		@plan = Plan.find_by!(id: @user.plan_id)
	end
	
	#creates a subscription on stripe when a user pays for the software
	def create
	 
	  @user = current_user
	  @plan = Plan.find_by!(id: @user.plan_id)
	  token = params[:stripeToken]

	  if Rails.env.production?
     		 Stripe.api_key = ENV['STRIPE_SECRET_KEY']
    else
     		 Stripe.api_key = ENV['STRIPE_SECRET_KEY'] 
     end

	  customer = Stripe::Customer.create(
	    email: current_user.email,
	    source: token
	  )

	  subscription = Stripe::Subscription.create(
	    :customer    => customer.id,
	    :plan 		 => @plan.stripe_id
	
	  )
	  	 @user.stripe_id  = customer.id
	  	 @user.sub_id = subscription.id
	     @user.save

		rescue Stripe::CardError => e
		  flash[:error] = e.message

		  redirect_to new_charge_path
	end

	def edit
  		@user = current_user
  	end
#updates the card details for your users
  	def update
  		
  		@user = current_user
	  	@plan = Plan.find_by!(id: @user.plan_id)
		if Rails.env.production?
     		 Stripe.api_key = ENV['STRIPE_SECRET_KEY']
    	else
     		 Stripe.api_key = ENV['STRIPE_SECRET_KEY']
     	end

		  token = params[:stripeToken]
		  customer = Stripe::Customer.retrieve(@user.stripe_id)
		  customer.source = token 
		  customer.save
		  redirect_to root_path
 	 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!

	def home
		@users = User.all
	end

	def about
	end

	def contact
	end

	def blog
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:owner, :show, :new, :create, :edit, :update, :destroy]

  def owner
    @students = Student.where(user: current_user)
  end

  # GET /students
  # GET /students.json
  def index
    @students = Student.all

  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
     @user = current_user
  end

  # GET /students/1/edit
  def edit
    @user = current_user
    @student = Student.find_by(id: params[:id])
    @plan = Splan.find_by!(id: @student.splan_id)
    Stripe.api_key = ENV['@user.access_code'] #replace with @user.access_code
    @publishable_key = ENV['@user.publishable_key'] #replace with @user.publishable_key
 end
  # POST /students
  # POST /students.json
  def create
    @student = current_user.students.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    

    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to owner_path, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:splan_id, :first_name, :last_name, :email, :phone_number, :street_address, :city, :state, :zip, :emergency_contact_name, :emergency_contact_phone, :emergency_contact_relationship, :emergency_medical_info, :belt_size, :uniform_size, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_active?(link_path)
		current_page?(link_path) ? "active" : ""
	end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/student_charges_helper.rb
module StudentChargesHelper
end

app/helpers/student_plans_helper.rb
module StudentPlansHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container-fluid">
		<nav class="pull-left">
			<ul>
				<li>
					<a href="#">
						Home
					</a>
				</li>
				<li>
					<a href="#">
						Company
					</a>
				</li>
				<li>
					<a href="#">
						Portfolio
					</a>
				</li>
				<li>
					<a href="#">
						Blog
					</a>
				</li>
			</ul>
		</nav>
		<p class="copyright pull-right">
		&copy; <a href="#">Academation 2017</a>
		</p>
	</div>
</footer>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="wrapper">

	<div class="sidebar" data-color="purple">
			<!--
		        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

		        Tip 2: you can also add an image using data-image tag
		    -->

		    <div class="logo">
		    	<a href="/" class="simple-text">
		    		Academation
		    	</a>
		    </div>

		    <div class="sidebar-wrapper">
		    	<ul class="nav">
		    		<li class="<%= is_active?('/') %>">
		    			<a href="/">
		    				<i class="material-icons">dashboard</i>
		    				<p>Dashboard</p>
		    			</a>
		    		</li>
		    		<li class="<%= is_active?('/users/edit') %>">
		    			<a href="/users/edit">
		    				<i class="material-icons">person</i>
		    				<p>User Profile</p>
		    			</a>
		    		</li>
		    		<li class="<%= is_active?('/owner') %>">
		    			<a href="/owner">
		    				<i class="material-icons">content_paste</i>
		    				<p>Students</p>
		    			</a>
		    		</li>
		    		<li class="<%= is_active?('#') %>">
		    			<a href="#">
		    				<i class="material-icons">library_books</i>
		    				<p>Reports</p>
		    			</a>
		    		</li>
		    		<li class="<%= is_active?('#') %>">
		    			<a href="#">
		    				<i class="material-icons">bubble_chart</i>
		    				<p>List Item</p>
		    			</a>
		    		</li>
		    		<li class="<%= is_active?('#') %>">
		    			<a href="#">
		    				<i class="material-icons">location_on</i>
		    				<p>List Item</p>
		    			</a>
		    		</li>
		    		<li class="<%= is_active?('#') %>">
		    			<a href="#">
		    				<i class="material-icons">unarchive</i>
		    				<p>Upgrade to PRO</p>
		    			</a>
		    		</li>
		    	</ul>
		    </div>
		</div>

		<div class="main-panel">
			<nav class="navbar navbar-transparent navbar-absolute">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="#">Dashboard</a>
					</div>
					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<li>
								<a href="#">
									<i class="material-icons">query_builder</i> <%= Time.now.strftime("%m/%d/%Y") %>
								</a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<i class="material-icons">person</i> <%= current_user.school_name %>
								</a>
								<ul class="dropdown-menu">
									<% if user_signed_in? %>
									<li class="nav-item"><%= link_to "Account", edit_user_registration_path %></li>
									<li class="nav-item"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
									<% else %>
									<li class="nav-item"><%= link_to "Sign Up", new_user_registration_path %></li>
									<li class="nav-item"><%= link_to "Login", new_user_session_path %></li>
									<% end %>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>Cosplay</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= tag :meta, :name=> 'stripe-key', :content => ENV["STRIPE_PUBLISHABLE_KEY"] %>
</head>

<body>

	<%= render 'layouts/header' %>

	<div class="content">
		<% if notice %>
		<div class="alert alert-success">
			<div class="container-fluid">
				<div class="alert-icon">
					<i class="material-icons">check</i>
				</div>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true"><i class="material-icons">clear</i></span>
				</button>
				<%= notice %>
			</div>
		</div>
		<% end %>
		<% if alert %>
		<div class="alert alert-danger">
			<div class="container-fluid">
				<div class="alert-icon">
					<i class="material-icons">check</i>
				</div>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true"><i class="material-icons">clear</i></span>
				</button>
				<%= alert %>
			</div>
		</div>
		<% end %>
		<%= yield %>		
	</div>

	<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Cosplay</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="background: linear-gradient(60deg, #ab47bc, #7b1fa2);">
    <nav class="navbar navbar-primary navbar-transparent">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#/dashboard">Academation</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to '<i class="material-icons">person_add</i> Register'.html_safe, new_user_registration_path, data: { turbolinks: false } %></li>
                    <li><%= link_to '<i class="material-icons">fingerprint</i> Login'.html_safe, new_user_session_path, data: { turbolinks: false }, class: "active" %></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="wrapper wrapper-full-page">
        <div class="full-page login-page" filter-color="black">
            <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
            <div class="content">
                <div class="container">

                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                            <div class="card card-login">
                                <div class="card-header text-center" data-background-color="purple">
                                    <h4 class="card-title">Login to Academation</h4>
                                    
                                </div>
                                
                                <div class="card-content">

                                    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                                    <% if notice %>
                                    <div class="alert alert-success">
                                        <div class="container-fluid">
                                            <div class="alert-icon">
                                                <i class="material-icons">check</i>
                                            </div>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true"><i class="material-icons">clear</i></span>
                                            </button>
                                            <%= notice %>
                                        </div>
                                    </div>
                                    <% end %>
                                    <% if alert %>
                                    <div class="alert alert-danger">
                                        <div class="container-fluid">
                                            <div class="alert-icon">
                                                <i class="material-icons">check</i>
                                            </div>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true"><i class="material-icons">clear</i></span>
                                            </button>
                                            <%= alert %>
                                        </div>
                                    </div>
                                    <% end %>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">email</i>
                                        </span>
                                        <div class="form-group is-empty"><%= f.email_field :email, autofocus: true, placeholder: "Email", class: "form-control" %>
                                            <span class="material-input"></span></div>
                                        </div>

                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">lock</i>
                                            </span>
                                            <div class="form-group is-empty"><%= f.password_field :password, autocomplete: "off", placeholder: "Password", class: "form-control" %>
                                                <span class="material-input"></span></div>
                                            </div>

                                            <% if devise_mapping.rememberable? -%>
                                            <div class="form-group">
                                              <%= f.check_box :remember_me %>
                                              <%= f.label :remember_me %>
                                          </div>
                                          <% end %>

                                          <%= render "devise/shared/links" %>

                                      </div>
                                      <div class="footer text-center">
                                        <div class="actions">
                                            <%= f.submit "Log in", class: "btn btn-primary" %>
                                        </div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="full-page-background"></div></div>
            </div>




            <div class="collapse navbar-collapse off-canvas-sidebar"><ul class="nav nav-mobile-menu">
                <li>
                    <a href="/#/dashboard">
                        <i class="material-icons">dashboard</i> Dashboard
                    </a>
                </li>
                <li class="">
                    <a href="register.html">
                        <i class="material-icons">person_add</i> Register
                    </a>
                </li>
                <li class=" active ">
                    <a href="login.html">
                        <i class="material-icons">fingerprint</i> Login
                    </a>
                </li>
                <li class="">
                    <a href="lock.html">
                        <i class="material-icons">lock_open</i> Lock
                    </a>
                </li>
            </ul>
        </div>
    </body>
    </html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Cosplay</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="background: linear-gradient(60deg, #ab47bc, #7b1fa2);">
    <nav class="navbar navbar-primary navbar-transparent">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#/dashboard">Academation</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to '<i class="material-icons">person_add</i> Register'.html_safe, new_user_registration_path, data: { turbolinks: false }, class: "active" %></li>
                    <li><%= link_to '<i class="material-icons">fingerprint</i> Login'.html_safe, new_user_session_path, data: { turbolinks: false } %></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="wrapper wrapper-full-page">
        <div class="full-page login-page" filter-color="black">
            <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
            <div class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                            <div class="card card-login">
                                <div class="card-header text-center" data-background-color="purple">
                                    <h4 class="card-title">Register</h4>
                                    
                                </div>
                                
                                <div class="card-content">

                                    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                                    <% if notice %>
                                    <div class="alert alert-success">
                                        <div class="container-fluid">
                                            <div class="alert-icon">
                                                <i class="material-icons">check</i>
                                            </div>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true"><i class="material-icons">clear</i></span>
                                            </button>
                                            <%= notice %>
                                        </div>
                                    </div>
                                    <% end %>
                                    <% if alert %>
                                    <div class="alert alert-danger">
                                        <div class="container-fluid">
                                            <div class="alert-icon">
                                                <i class="material-icons">check</i>
                                            </div>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true"><i class="material-icons">clear</i></span>
                                            </button>
                                            <%= alert %>
                                        </div>
                                    </div>
                                    <% end %>

                                     <div class="input-group">
                                        <span class="input-group-addon">
                                            
                                        </span>
                                        <%= f.collection_select(:plan_id, Plan.all, :id, :name, class: "form-control") %>
                                            <span class="material-input"></span>
                                        </div>

                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">email</i>
                                        </span>
                                        <div class="form-group is-empty"><%= f.email_field :email, autofocus: true, placeholder: "Email", class: "form-control" %>
                                            <span class="material-input"></span></div>
                                        </div>

                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">lock</i>
                                            </span>
                                            <div class="form-group is-empty"><%= f.password_field :password, autocomplete: "off", placeholder: "Password", class: "form-control" %>
                                                <span class="material-input"></span></div>
                                            </div>

                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="material-icons">lock</i>
                                                </span>
                                                <div class="form-group is-empty"><%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Confirm Password", class: "form-control" %>
                                                    <span class="material-input"></span></div>
                                                </div>

                                                <% if devise_mapping.rememberable? -%>
                                                <div class="form-group">
                                                  <%= f.check_box :remember_me %>
                                                  <%= f.label :remember_me %>
                                              </div>
                                              <% end %>

                                          </div>
                                          <div class="footer text-center">
                                            <div class="actions">
                                                <%= f.submit "Log in", class: "btn btn-primary" %>
                                            </div>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="full-page-background"></div></div>
            </div>


            <div class="collapse navbar-collapse off-canvas-sidebar"><ul class="nav nav-mobile-menu">
                <li class="/users/sign_up">
                    <a href="register.html">
                        <i class="material-icons">person_add</i> Register
                    </a>
                </li>
                <li class="">
                    <a href="/users/sign_in">
                        <i class="material-icons">fingerprint</i> Login
                    </a>
                </li>
            </ul>
        </div>
    </body>
    </html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/blog.html.erb
<h1>Pages#blog</h1>
<p>Find me in app/views/pages/blog.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>